config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/nodejs/node:
      branch: main
      repo: https://github.com/nodejs/node
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/nodejs/node git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-salmon-oriole.sh
        container: qc.acc_slaphappy-rust-panda
  QC.Doc:
    repos:
      github.com/nodejs/node find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-lilac-bear.sh
        container: qc.doc_geeky-pink-flamingo
      github.com/nodejs/node git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ultramarine-snake.sh
        container: qc.doc_homely-champagne-russel
      github.com/nodejs/node markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-auburn-spitz.sh
        container: qc.doc_silly-cinnamon-peccary
      github.com/nodejs/node restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-tetra.sh
        container: qc.doc_ugly-lilac-seal
  QC.Lic:
    repos:
      github.com/nodejs/node licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-malachite-quoll.sh
        container: qc.lic_muzzy-cream-quetzal
  QC.Sec:
    repos:
      github.com/nodejs/node bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-green-argentino.sh
        container: qc.sec_whiny-plum-vole
  QC.Sty:
    repos:
      github.com/nodejs/node flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-black-owl.sh
        container: qc.sty_tacky-razzmatazz-saola
      github.com/nodejs/node hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amaranth-cattle.sh
        container: qc.sty_gloppy-russet-capybara
      github.com/nodejs/node jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-flax-clam.sh
        container: qc.sty_ready-periwinkle-pinscher
      github.com/nodejs/node rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-turquoise-salamander.sh
        container: qc.sty_chewy-bronze-moose
  QC.Ver:
    repos:
      github.com/nodejs/node get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amaranth-mayfly.sh
        container: qc.ver_squirrely-lavender-tarsier
timeout: 5400
