config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/nodejs/node:
      branch: main
      repo: https://github.com/nodejs/node
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/nodejs/node git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-plum-squirt.sh
        container: qc.acc_slimy-gold-gharial
  QC.Doc:
    repos:
      github.com/nodejs/node find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-heliotrope-spaniel.sh
        container: qc.doc_homely-thistle-snail
      github.com/nodejs/node git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-bronze-bison.sh
        container: qc.doc_sickly-wheat-tetra
      github.com/nodejs/node markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-eggplant-owl.sh
        container: qc.doc_stuffy-crimson-terrier
      github.com/nodejs/node restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-purple-dodo.sh
        container: qc.doc_squeaky-copper-centipede
  QC.Lic:
    repos:
      github.com/nodejs/node licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ruby-moth.sh
        container: qc.lic_jumpy-silver-bloodhound
  QC.Sec:
    repos:
      github.com/nodejs/node bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-black-frigatebird.sh
        container: qc.sec_shabby-corn-quoll
  QC.Sty:
    repos:
      github.com/nodejs/node flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-salmon-scorpion.sh
        container: qc.sty_cheeky-ecru-dodo
      github.com/nodejs/node hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-zucchini-akita.sh
        container: qc.sty_frumpy-sepia-binturong
      github.com/nodejs/node jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cinnamon-wolfhound.sh
        container: qc.sty_randy-thistle-mule
      github.com/nodejs/node rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-goldenrod-bird.sh
        container: qc.sty_cloudy-myrtle-mayfly
  QC.Ver:
    repos:
      github.com/nodejs/node get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-burgundy-fossa.sh
        container: qc.ver_lovely-brass-eel
timeout: 5400
